#!/usr/bin/env ruby
# Copyright (C) 2003-2010 Wang Pengcheng <wpc0000@gmail.com>
# , released under the MIT license
# You may obtain a template of the MIT License at
# http://www.opensource.org/licenses/mit-license.php
$KCODE = 'utf8'

system 'rake'

args = '['+ARGV.join(' ')+']'
args.gsub!(',','--**comma**--')
args ='' if ARGV.length <= 0
system 'rake','hg:ci'+args
system 'rake','hg:push'

Dir.chdir('./wiki')
system 'hg','addremove'
system 'rake','hg:ci'+args
system 'rake','hg:push','--insecure'
